---
version: 2
project_name: tfprovidercheck
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*
builds:
  - binary: tfprovidercheck
    main: cmd/tfprovidercheck/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/suzuki-shunsuke/tfprovidercheck/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/suzuki-shunsuke/tfprovidercheck/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/suzuki-shunsuke/tfprovidercheck/compare/{{.PreviousTag}}...{{.Tag}}

sboms:
  - id: default
    disable: false

homebrew_casks:
  - repository:
      owner: suzuki-shunsuke
      name: homebrew-tfprovidercheck
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/suzuki-shunsuke/tfprovidercheck
    description: Censor Terraform Providers
    license: MIT
    skip_upload: true
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfprovidercheck"]
          end

scoops:
  - description: Censor Terraform Providers
    license: MIT
    skip_upload: true
    repository:
      owner: suzuki-shunsuke
      name: scoop-bucket
