---
name: autofix.ci
on: pull_request
permissions: {}
jobs:
  autofix:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: suzuki-shunsuke/go-autofix-action@9a8682f2dc2a935fe2a2ac96deb03de2dfcb872e # v0.1.13
        with:
          aqua_version: v2.62.1
          takumi_guard_bot_id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
