---
name: test
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  status-check:
    runs-on: ubuntu-26.04
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - run: exit 1

  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@981264a9d35fe1edc3426aedc1bb94bc3e62264a # v6.1.0
    with:
      aqua_version: v2.64.0
      golangci-lint-timeout: 120s
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      pull-requests: write
      contents: read
      id-token: write
